const CONSTANTS = {
  REQUEST_LISTHOTELS: 'REQUEST_LISTHOTELS',
  RECEIVE_LISTHOTELS: 'RECEIVE_LISTHOTELS',
  REQUEST_HOTELDETAILS: 'REQUEST_HOTELDETAILS',
  RECEIVE_HOTELDETAILS: 'RECEIVE_HOTELDETAILS',
};

export default CONSTANTS;
